version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  python: circleci/python@2.0.3
workflows:
  version: 2
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          app-name: $HEROKU_PRODUCTION_APP_NAME
          requires:
            - build
          filters:
            branches:
              only: main
      - heroku/deploy-via-git:
          app-name: $HEROKU_STAGING_APP_NAME
          requires:
            - build
          filters:
            branches:
              only: staging 
      - heroku/deploy-via-git:
          app-name: $HEROKU_DEV_APP_NAME
          requires:
            - build
          filters:
            branches:
              only: dev
jobs:
 build:
   machine:
    image: "ubuntu-2004:current"
   steps:
     - run:
        name: "Install Python"
        command: sudo apt update && sudo apt upgrade -y
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt install python@3.9

     - checkout
    #  - run: |
        #  echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

    #  - run: TAG="0.1.${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH}" && docker build -t shantanu2307/devops_app:$TAG . && docker push shantanu2307/devops_app:$TAG
     - python/install-packages:
        pip-dependency-file: requirements.txt
        pkg-manager: pip
     - run:
        name: "Run tests"
        command: pytest --html=test_reports/report.html
     - store_test_results:
        path: test_reports
     - store_artifacts:
        path: test_reports
        