version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  version: 2
  heroku_deploy:
    jobs:
      - build
      - dockerise
      - heroku/deploy-via-git:
          app-name: $HEROKU_PRODUCTION_APP_NAME
          requires:
            - build
            - dockerise
          filters:
            branches:
              only: main
      - heroku/deploy-via-git:
          app-name: $HEROKU_STAGING_APP_NAME
          requires:
            - build
          filters:
            branches:
              only: staging 
      - heroku/deploy-via-git:
          app-name: $HEROKU_DEV_APP_NAME
          requires:
            - build
          filters:
            branches:
              only: dev
jobs:
 dockerise:
   machine:
     image: "ubuntu-2004:current"
   steps:
     - checkout
     - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     - run: TAG="0.1.${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH}" && docker build -t shantanu2307/devops_app:$TAG . && docker push shantanu2307/devops_app:$TAG
     
 build:
   machine:
    image: "ubuntu-2004:current"
   steps:
     - run:
        name: "Install Python"
        command: sudo apt install python3

     - checkout
     - run:
        name: "Install Dependencies"
        command: pip3 install -r requirements.txt
     - run:
        name: "Run tests"
        command: python3 -m pytest --html=test_reports/report.html
     - store_test_results:
        path: test_reports
     - store_artifacts:
        path: test_reports
        