version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  version: 2
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          app-name: $HEROKU_PRODUCTION_APP_NAME
          requires:
            - build
          filters:
            branches:
              only: main
      - heroku/deploy-via-git:
          app-name: $HEROKU_STAGING_APP_NAME
          requires:
            - build
          filters:
            branches:
              only: staging 
      - heroku/deploy-via-git:
          app-name: $HEROKU_DEV_APP_NAME
          requires:
            - build
          filters:
            branches:
              only: dev
jobs:
 build:
   machine:
    image: "ubuntu-2004:current"
    docker_layer_caching: true 
   steps:
     - checkout
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: TAG="0.1.${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH}" && docker build -t shantanu2307/devops_app:$TAG . && docker push shantanu2307/devops_app:$TAG


